Import('env')
env = env.Clone()

libtcod = '/Coding/libtcod-1.5.1/'

env.Append(CPPPATH=[libtcod + 'include'],
           LIBPATH=[libtcod + 'lib'],
           LIBS=['libtcod-mingw'],
           CXXFLAGS=['-std=c++0x', '-Wall'])

sources = [
  'main.cpp',
  'map.cpp',
  'entity.cpp',
  'event.cpp',
  ]

prog = env.Program('rl', sources) 

for dll in ['SDL.dll', 'libtcod-mingw.dll', 'terminal.png']:
  act = env.Command(dll, libtcod + dll, Copy("$TARGET", "$SOURCE"))
  env.Depends(act, prog)


