Import('env')
env = env.Clone()

sources = [
  'map.cpp',
  'entity.cpp',
  'event.cpp',
  'game.cpp',
  'msg_log.cpp',
  'pc.cpp',
  ]

# apt-get install yaml-cpp-dev
# https://github.com/jbeder/yaml-cpp/wiki/Tutorial

env.Append(CFLAGS=' -Wall -g', CXXFLAGS=' -Wall -g')
rl_lib = env.Library('rl-lib', sources) 

if True:
    # termbox "curses" terminal UI
    env = env.Clone()
    env.Append(CPPPATH=['.', '../../usr/include'],
               LIBPATH=['../../usr/lib'],
               LIBS=[rl_lib, 'termbox', 'yaml-cpp'])
    env.Program('rl-term', ['ui/term/main.cpp'])

if False:
    # 'main.cpp',
    for dll in ['SDL.dll', 'libtcod-mingw.dll', 'terminal.png']:
      act = env.Command(dll, libtcod + dll, Copy("$TARGET", "$SOURCE"))
      env.Depends(prog, act)

    libtcod = '/Coding/libtcod-1.5.1/'
    env.Append(CPPPATH=[libtcod + 'include'],
               LIBPATH=[libtcod + 'lib'],
               LIBS=['libtcod-mingw'],
               CXXFLAGS=['-std=c++0x', '-Wall'],
               CPPDEFINES=['__STDC_FORMAT_MACROS'])

